# Generated by Django 5.1.4 on 2025-01-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('project_id', models.IntegerField(unique=True)),
                ('last_assessed', models.DateTimeField(auto_now=True)),
                ('variables_protected', models.BooleanField()),
                ('runners_secure', models.BooleanField()),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=50)),
            ],
        ),
    ]
